name: Build & Test

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build on Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
    - run: yarn run test
      env:
        CI: true
