name: Build & Test & Push to Github
on:
  push:
    branches:
      - next
      - bugfix/github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init Node env
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: GScan Theme
        run: yarn run test
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          publish_branch: dist
